"""keep the counterparty on a booking

Revision ID: 006c7dae1f2e
Revises: 96a78da89c2e
Create Date: 2026-08-19 20:14:22.540721

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate emits fastapi_users_db_sqlalchemy.generics.GUID for user IDs but
# forgets to import it, so the import is wired into this template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '006c7dae1f2e'
down_revision: Union[str, Sequence[str], None] = '96a78da89c2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('counterparty_name', sa.String(length=200), nullable=True))
    op.add_column('transactions', sa.Column('counterparty_iban', sa.String(length=34), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'counterparty_iban')
    op.drop_column('transactions', 'counterparty_name')
    # ### end Alembic commands ###
