"""add_auto_booked_and_budget_positions

Revision ID: 3ca378cfe07a
Revises: bf4ac6baa63a
Create Date: 2026-08-02 16:46:48.166014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '3ca378cfe07a'
down_revision: Union[str, Sequence[str], None] = 'bf4ac6baa63a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default, sonst scheitert NOT NULL an vorhandenen Zeilen —
    # plan_positions ist bereits gefüllt. Bleibt stehen, er entspricht dem
    # Default im Modell.
    op.add_column(
        'plan_positions',
        sa.Column('is_budget', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.add_column(
        'transactions',
        sa.Column('auto_booked', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transactions', 'auto_booked')
    op.drop_column('plan_positions', 'is_budget')
    # ### end Alembic commands ###
