"""add_transactions_and_default_account

Revision ID: 4c9422844fa4
Revises: 1ebb9f2f3560
Create Date: 2026-08-02 14:07:26.547692

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4c9422844fa4'
down_revision: Union[str, Sequence[str], None] = '1ebb9f2f3560'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transactions',
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('counter_account_id', sa.Uuid(), nullable=True),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('note', sa.String(length=200), nullable=True),
    sa.Column('category', sa.Enum('income', 'housing', 'insurance', 'groceries', 'health', 'mobility', 'communication', 'children', 'subscriptions', 'leisure', 'vacation', 'pocket_money', 'reserves', 'debt_repayment', 'investment', 'legal', 'work', name='category', native_enum=False, length=20), nullable=True),
    sa.Column('block', sa.Enum('income', 'needs', 'wants', 'savings', name='block', native_enum=False, length=20), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('external_ref', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('counter_account_id IS NOT NULL OR (category IS NOT NULL AND block IS NOT NULL)', name='ck_transaction_purpose_unless_transfer'),
    sa.CheckConstraint('counter_account_id IS NULL OR counter_account_id <> account_id', name='ck_transaction_transfer_needs_two_accounts'),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['counter_account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['plan_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_occurred_on'), 'transactions', ['occurred_on'], unique=False)
    # server_default, sonst scheitert NOT NULL an bereits vorhandenen Zeilen.
    # Bleibt stehen: er entspricht dem Default im Modell.
    op.add_column(
        'accounts',
        sa.Column('is_default', sa.Boolean(), nullable=False, server_default=sa.false()),
    )
    op.create_index('uq_account_one_default_per_owner', 'accounts', ['owner_id'], unique=True, postgresql_where=sa.text('is_default'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('uq_account_one_default_per_owner', table_name='accounts', postgresql_where=sa.text('is_default'))
    op.drop_column('accounts', 'is_default')
    op.drop_index(op.f('ix_transactions_occurred_on'), table_name='transactions')
    op.drop_table('transactions')
    # ### end Alembic commands ###
