"""add_payment_method_to_commitments

Revision ID: 4da5524d36bf
Revises: c2f8b31d4a67
Create Date: 2026-08-01 06:14:39.835940

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '4da5524d36bf'
down_revision: Union[str, Sequence[str], None] = 'c2f8b31d4a67'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('commitments', sa.Column('payment_method', sa.Enum('withdrawal', 'transfer', 'standing_order', 'direct_debit', 'special', name='paymentmethod', native_enum=False, length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('commitments', 'payment_method')
    # ### end Alembic commands ###
