"""add pass through to commitments and positions

Revision ID: 59b5c53d658b
Revises: 9d1a412fc674
Create Date: 2026-08-03 05:57:17.994050

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '59b5c53d658b'
down_revision: Union[str, Sequence[str], None] = '9d1a412fc674'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default ist Pflicht: beide Tabellen haben Zeilen, NOT NULL ohne
    # Vorgabe scheitert daran. `false` ist auch fachlich richtig — bestehende
    # Posten sind normale Posten, durchlaufend markiert man von Hand.
    for table in ('commitments', 'plan_positions'):
        op.add_column(
            table,
            sa.Column(
                'pass_through',
                sa.Boolean(),
                nullable=False,
                server_default=sa.false(),
            ),
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('plan_positions', 'pass_through')
    op.drop_column('commitments', 'pass_through')
    # ### end Alembic commands ###
