"""add imported entries for the parking area

Revision ID: 96a78da89c2e
Revises: e2f4b8a91c53
Create Date: 2026-08-19 09:09:43.588985

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate emits fastapi_users_db_sqlalchemy.generics.GUID for user IDs but
# forgets to import it, so the import is wired into this template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '96a78da89c2e'
down_revision: Union[str, Sequence[str], None] = 'e2f4b8a91c53'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('imported_entries',
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('imported_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('account_id', sa.Uuid(), nullable=False),
    sa.Column('external_ref', sa.String(length=200), nullable=False),
    sa.Column('occurred_on', sa.Date(), nullable=False),
    sa.Column('value_on', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('incoming', sa.Boolean(), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_iban', sa.String(length=34), nullable=True),
    sa.Column('purpose', sa.String(length=1000), nullable=True),
    sa.Column('position_id', sa.Uuid(), nullable=True),
    sa.Column('category', sa.Enum('household.groceries', 'household.clothing', 'household.healthcare', 'household.personal_care', 'household.cleaning', 'housing.rent', 'housing.utilities', 'housing.repairs', 'housing.interior', 'housing.outdoor', 'housing.insurance', 'transport.public', 'transport.fuel', 'transport.repairs', 'transport.fines', 'transport.purchase', 'transport.insurance', 'children.care', 'children.school', 'children.allowance', 'leisure.vacation', 'leisure.hobbies', 'leisure.entertainment', 'leisure.memberships', 'leisure.dining', 'leisure.subscriptions', 'personal.insurance', 'personal.communication', 'personal.work', 'personal.legal', 'income.earned', 'income.benefits', 'income.interest', 'income.other', 'finance.savings', 'finance.debt', 'finance.investment', 'finance.fees', 'finance.settlement', name='category', native_enum=False, length=40), nullable=True),
    sa.Column('block', sa.Enum('income', 'needs', 'wants', 'savings', name='block', native_enum=False, length=20), nullable=True),
    sa.Column('discarded_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['imported_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['plan_positions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('account_id', 'external_ref', name='uq_imported_entry_ref_per_account')
    )
    op.create_index(op.f('ix_imported_entries_occurred_on'), 'imported_entries', ['occurred_on'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_imported_entries_occurred_on'), table_name='imported_entries')
    op.drop_table('imported_entries')
    # ### end Alembic commands ###
