"""add counts as available to accounts

Revision ID: 9d1a412fc674
Revises: 3ca378cfe07a
Create Date: 2026-08-03 05:10:32.609014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = '9d1a412fc674'
down_revision: Union[str, Sequence[str], None] = '3ca378cfe07a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default ist Pflicht: die Tabelle hat Zeilen, und NOT NULL ohne
    # Vorgabe scheitert daran. `true` ist auch fachlich die richtige Annahme —
    # ein Konto zählt als verfügbar, bis jemand es anders sagt.
    op.add_column(
        'accounts',
        sa.Column(
            'counts_as_available',
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('accounts', 'counts_as_available')
    # ### end Alembic commands ###
