"""Add household, commitment, plan and position models

Revision ID: aafe15ae453d
Revises: 77769f19cbd9
Create Date: 2026-07-28 12:21:56.596746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'aafe15ae453d'
down_revision: Union[str, Sequence[str], None] = '77769f19cbd9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('households',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('commitments',
    sa.Column('owner_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('type', sa.Enum('CONTRACT', 'SAVINGS_GOAL', 'DEBT', name='commitmenttype', native_enum=False, length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('category', sa.Enum('INCOME', 'HOUSING', 'INSURANCE', 'GROCERIES', 'HEALTH', 'MOBILITY', 'COMMUNICATION', 'CHILDREN', 'SUBSCRIPTIONS', 'LEISURE', 'VACATION', 'POCKET_MONEY', 'RESERVES', 'DEBT_REPAYMENT', 'INVESTMENT', name='category', native_enum=False, length=20), nullable=False),
    sa.Column('rhythm', sa.Enum('MONTHLY', 'QUARTERLY', 'BIANNUAL', 'ANNUAL', name='rhythm', native_enum=False, length=20), nullable=False),
    sa.Column('first_month', sa.Integer(), nullable=True),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('target_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('remaining_debt', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name='ck_commitment_due_day'),
    sa.CheckConstraint('first_month IS NULL OR first_month BETWEEN 1 AND 12', name='ck_commitment_first_month'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('household_members',
    sa.Column('household_id', sa.Uuid(), nullable=False),
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('role', sa.Enum('OWNER', 'MEMBER', name='role', native_enum=False, length=20), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('household_id', 'user_id', name='uq_household_member')
    )
    op.create_table('plans',
    sa.Column('user_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('month', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('DRAFT', 'CONFIRMED', name='planstatus', native_enum=False, length=20), nullable=False),
    sa.Column('target_needs', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_wants', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('target_savings', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('buffer_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('month BETWEEN 1 AND 12', name='ck_plan_month'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'year', 'month', name='uq_plan_user_month')
    )
    op.create_table('plan_positions',
    sa.Column('plan_id', sa.Uuid(), nullable=False),
    sa.Column('commitment_id', sa.Uuid(), nullable=True),
    sa.Column('household_id', sa.Uuid(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=False),
    sa.Column('amount_planned', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('amount_actual', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('category', sa.Enum('INCOME', 'HOUSING', 'INSURANCE', 'GROCERIES', 'HEALTH', 'MOBILITY', 'COMMUNICATION', 'CHILDREN', 'SUBSCRIPTIONS', 'LEISURE', 'VACATION', 'POCKET_MONEY', 'RESERVES', 'DEBT_REPAYMENT', 'INVESTMENT', name='category', native_enum=False, length=20), nullable=False),
    sa.Column('block', sa.Enum('INCOME', 'NEEDS', 'WANTS', 'INVESTMENT', 'SAVINGS', name='block', native_enum=False, length=20), nullable=False),
    sa.Column('due_day', sa.Integer(), nullable=False),
    sa.Column('payment_method', sa.Enum('WITHDRAWAL', 'TRANSFER', 'STANDING_ORDER', 'DIRECT_DEBIT', 'SPECIAL', name='paymentmethod', native_enum=False, length=20), nullable=True),
    sa.Column('manually_changed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('due_day BETWEEN 1 AND 31', name='ck_position_due_day'),
    sa.ForeignKeyConstraint(['commitment_id'], ['commitments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['household_id'], ['households.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['plan_id'], ['plans.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_positions')
    op.drop_table('plans')
    op.drop_table('household_members')
    op.drop_table('commitments')
    op.drop_table('households')
    # ### end Alembic commands ###
