"""add access level to household members

Revision ID: b09e2252b8da
Revises: 59b5c53d658b
Create Date: 2026-08-03 06:31:16.371267

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'b09e2252b8da'
down_revision: Union[str, Sequence[str], None] = '59b5c53d658b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # server_default ist Pflicht: die Tabelle hat Zeilen. `plan` ist auch die
    # richtige Vorgabe — niemand soll durch eine Migration plötzlich Einblick
    # ins Buch des anderen bekommen, den er nie gegeben hat.
    op.add_column(
        'household_members',
        sa.Column(
            'grants_access',
            sa.Enum('plan', 'view', 'edit', name='accesslevel',
                    native_enum=False, length=20),
            nullable=False,
            server_default='plan',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('household_members', 'grants_access')
    # ### end Alembic commands ###
