"""add_account_to_commitments_and_positions

Revision ID: bf4ac6baa63a
Revises: 4c9422844fa4
Create Date: 2026-08-02 16:14:11.505835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'bf4ac6baa63a'
down_revision: Union[str, Sequence[str], None] = '4c9422844fa4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Namen ausgeschrieben: Autogenerate setzt hier None, und dann scheitert
    # der downgrade() an einem Constraint ohne Namen.
    op.add_column('commitments', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_commitments_account_id',
        'commitments', 'accounts', ['account_id'], ['id'], ondelete='SET NULL',
    )
    op.add_column('plan_positions', sa.Column('account_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(
        'fk_plan_positions_account_id',
        'plan_positions', 'accounts', ['account_id'], ['id'], ondelete='SET NULL',
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_plan_positions_account_id', 'plan_positions', type_='foreignkey')
    op.drop_column('plan_positions', 'account_id')
    op.drop_constraint('fk_commitments_account_id', 'commitments', type_='foreignkey')
    op.drop_column('commitments', 'account_id')
    # ### end Alembic commands ###
