"""add counter account to commitments and positions

Revision ID: c2563f609652
Revises: b09e2252b8da
Create Date: 2026-08-03 08:07:38.311445

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'c2563f609652'
down_revision: Union[str, Sequence[str], None] = 'b09e2252b8da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Nullable, deshalb ohne server_default — es gibt nichts zu füllen.
    # Die Fremdschlüssel werden **benannt**: Autogenerate lässt den Namen offen,
    # und `drop_constraint(None, ...)` scheitert im Downgrade.
    for table in ('commitments', 'plan_positions'):
        op.add_column(table, sa.Column('counter_account_id', sa.Uuid(), nullable=True))
        op.create_foreign_key(
            f'fk_{table}_counter_account_id_accounts',
            table,
            'accounts',
            ['counter_account_id'],
            ['id'],
            ondelete='SET NULL',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for table in ('plan_positions', 'commitments'):
        op.drop_constraint(
            f'fk_{table}_counter_account_id_accounts', table, type_='foreignkey'
        )
        op.drop_column(table, 'counter_account_id')
