"""Add commitment type constraints and position change log

Revision ID: da1f8e62e34f
Revises: aafe15ae453d
Create Date: 2026-07-28 12:43:04.766117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

# Autogenerate erzeugt fastapi_users_db_sqlalchemy.generics.GUID für User-IDs,
# vergisst aber den Import. Deshalb fest im Template.
import fastapi_users_db_sqlalchemy


# revision identifiers, used by Alembic.
revision: str = 'da1f8e62e34f'
down_revision: Union[str, Sequence[str], None] = 'aafe15ae453d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('plan_position_changes',
    sa.Column('position_id', sa.Uuid(), nullable=False),
    sa.Column('changed_by_id', fastapi_users_db_sqlalchemy.generics.GUID(), nullable=False),
    sa.Column('field', sa.String(length=50), nullable=False),
    sa.Column('old_value', sa.String(length=200), nullable=True),
    sa.Column('new_value', sa.String(length=200), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['position_id'], ['plan_positions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Check-Constraints vergleicht Autogenerate nicht — von Hand ergänzt.
    op.create_check_constraint(
        "ck_commitment_target_only_for_savings_goal",
        "commitments",
        "type = 'savings_goal' OR (target_amount IS NULL AND target_date IS NULL)",
    )
    op.create_check_constraint(
        "ck_commitment_remaining_debt_only_for_debt",
        "commitments",
        "type = 'debt' OR remaining_debt IS NULL",
    )
    op.create_check_constraint(
        "ck_commitment_first_month_required",
        "commitments",
        "rhythm = 'monthly' OR first_month IS NOT NULL",
    )


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_constraint("ck_commitment_first_month_required", "commitments", type_="check")
    op.drop_constraint("ck_commitment_remaining_debt_only_for_debt", "commitments", type_="check")
    op.drop_constraint("ck_commitment_target_only_for_savings_goal", "commitments", type_="check")

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('plan_position_changes')
    # ### end Alembic commands ###
